# Generated by Django 3.0.2 on 2020-01-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='url',
        ),
        migrations.AlterField(
            model_name='images',
            name='imgHash',
            field=models.CharField(editable=False, max_length=256, unique=True),
        ),
    ]
